### ISSUE TITLE
Unable to ping from ep1 to ep2

### ISSUE THREAD

**Issue by clu2xlu** [futurewei-cloud/mizar#124]

**Comment by clu2xlu** [comment]
DEBUG:root:Allocated ID for simple-ep-ep2 as bbab572a
DEBUG:root:files ns ['cni-84155cf7-fb4c-aecf-ca53-23fc9b861002']
DEBUG:root:Created namespace mizar-bbab572a from /var/run/netns/cni-84155cf7-fb4c-aecf-ca53-23fc9b861002
DEBUG:root:Move interface eth-bbab572a to netns mizar-bbab572a
DEBUG:root:Rename interface to eth0
INFO:root:Bring loopback device in netns mizar-bbab572a up
INFO:root:Bring endpoint's interface eth0 up in netns mizar-bbab572a
INFO:root:Bring veth interface veth-bbab572a up and set mtu to 9000
INFO:root:load_transit_agent_xdp: /trn_bin/transit -s 172.17.0.2  load-agent-xdp -i 'veth-bbab572a' -j '{"xdp_path": "/trn_xdp/trn_agent_xdp_ebpf_debug.o", "pcapfile": "veth-bbab572a.pcap"}'
INFO:root:load_transit_agent_xdp returns None /bin/sh: 1: /trn_bin/transit: not found

DEBUG:kubernetes.client.rest:response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"endpoints.mizar.com \"simple-ep-ep2\" not found","reason":"NotFound","details":{"name":"simple-ep-ep2","group":"mizar.com","kind":"endpoints"},"code":404}

**Comment by zasherif** [comment]
We do have a timing issue here when loading the docker images, having the transit program not present

**Comment by phudtran** [comment]
This was actually a dev environment issue. 

Rsync with the — delete option was being used. The local dev machine did not have mizar compiled whereas the remote test machine did. 

When changes were rsynced with the remote, the mizar binaries were deleted, as they did not match what was on the local machine.

In our Kind cluster yaml file, we mount the ~/mizar folder onto the Kind nodes. Since the compiled binaries don’t exist on the machine, they also don’t exist on the Kind nodes.

I think we can close this issue. I worked with Cathy on Friday we were able to get everything working with ping going.
